[package]
name = "hbbs-enterprise"
version = "1.2.0"
authors = ["rustdesk <info@rustdesk.com>"]
edition = "2021"
build = "build.rs"
default-run = "hbbs-enterprise"
description = "RustDesk Enterprise Server with advanced features"

[[bin]]
name = "hbbs-enterprise"
path = "src/enterprise_main.rs"

[[bin]]
name = "hbbr-enterprise"
path = "src/enterprise_relay_server.rs"

[[bin]]
name = "rustdesk-utils-enterprise"
path = "src/utils.rs"

[dependencies]
# 原有依赖
hbb_common = { path = "libs/hbb_common" }
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
lazy_static = "1.4"
clap = "2"
rust-ini = "0.18"
minreq = { version = "2.4", features = ["punycode"] }
machine-uid = "0.2"
mac_address = "1.1.5"
whoami = "1.2"
base64 = "0.13"
sqlx = { version = "0.6", features = [ "runtime-tokio-rustls", "sqlite", "macros", "chrono", "json" ] }
deadpool = "0.8"
async-trait = "0.1"
async-speed-limit = { git = "https://github.com/open-trade/async-speed-limit" }
uuid = { version = "1.0", features = ["v4"] }
chrono = "0.4"
once_cell = "1.8"
sodiumoxide = "0.2"
tokio-tungstenite = "0.17"
tungstenite = "0.17"
regex = "1.4"
http = "0.2"
flexi_logger = { version = "0.22", features = ["async", "use_chrono_for_offset", "dont_minimize_extra_stacks"] }
ipnetwork = "0.20"
local-ip-address = "0.5.1"
dns-lookup = "1.0.8"
ping = "0.4.0"

# 企业版新增依赖
axum = { version = "0.6", features = ["headers", "ws", "multipart"] }
tower = "0.4"
tower-http = { version = "0.4", features = ["fs", "trace", "cors", "compression-gzip"] }
bcrypt = "0.14"
jsonwebtoken = "8"
headers = "0.3"
rand = "0.8"
rust-ini = "0.18"
totp-rs = "4.0"
qrcode = "0.12"
image = "0.24"
lettre = "0.10"
handlebars = "4.3"
mime_guess = "2.0"

# 数据库支持
sqlx-migrate = "0.6"

# 监控和指标
prometheus = "0.13"
metrics = "0.20"
metrics-prometheus = "0.5"

# 配置管理
config = "0.13"
dotenvy = "0.15"

# 日志增强
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
reqwest = { git = "https://github.com/rustdesk-org/reqwest", features = ["blocking", "socks", "json", "native-tls", "gzip"], default-features=false }

[target.'cfg(not(any(target_os = "macos", target_os = "windows")))'.dependencies]
reqwest = { git = "https://github.com/rustdesk-org/reqwest", features = ["blocking", "socks", "json", "rustls-tls", "rustls-tls-native-roots", "gzip"], default-features=false }

[build-dependencies]
hbb_common = { path = "libs/hbb_common" }

[workspace]
members = ["libs/hbb_common"]
exclude = ["ui"]

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
strip = true

[features]
default = ["enterprise"]
enterprise = []
monitoring = ["prometheus", "metrics"]
email-notifications = ["lettre"]
ldap = []

[package.metadata.docs.rs]
features = ["enterprise", "monitoring"]